"""Labels that keep source, generated, and decision data distinguishable."""

SOURCE_DATASET = "SOURCE_DATASET"
GENERATED_LIFECYCLE = "GENERATED_LIFECYCLE"
GENERATED_COMPLAINT = "GENERATED_COMPLAINT"
DERIVED_STATE = "DERIVED_STATE"
MODEL_OUTPUT = "MODEL_OUTPUT"
POLICY_DECISION = "POLICY_DECISION"
HUMAN_DECISION = "HUMAN_DECISION"
RESOLUTION_RESULT = "RESOLUTION_RESULT"

ALL_PROVENANCE = frozenset(
    {
        SOURCE_DATASET,
        GENERATED_LIFECYCLE,
        GENERATED_COMPLAINT,
        DERIVED_STATE,
        MODEL_OUTPUT,
        POLICY_DECISION,
        HUMAN_DECISION,
        RESOLUTION_RESULT,
    }
)
